apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deploy-app-pipeline
  description: "Deploy App with OpenShift Pipeline"
  annotations:
    backstage.io/kubernetes-id: tekton-demo
    backstage.io/kubernetes-namespace: pipeline-demo  # Update to your namespace if needed
    janus-idp.io/tekton-pipeline: deploy-app-pipeline
    janus-idp.io/tekton-enabled: 'true'
    backstage.io/kubernetes-label-selector: 'app=web'
    app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"Deployment"}]'
    backstage.io/source-location: url:https://github.com/gaikwadgaurav12495/test.git
    backstage.io/techdocs-ref: url:https://github.com/gaikwadgaurav12495/test.git
    janus-idp.io/tekton: backstage
    tekton.dev/pipeline: "deploy-app-pipeline"  
    backstage.io/pipeline-trigger: "true" 
  labels:
    backstage.io/kubernetes-id: tekton-demo
    backstage.io/kubernetes-namespace: pipeline-demo  
  tags:
    - tekton
    - pipeline
    - demo
  links:
    - url: https://console-openshift-console.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com/dev-pipelines/ns/pipeline-demo
      title: OpenShift Pipelines (Pipeline-Demo)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "dev-hub-team"

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: "System for managing the backstage project"
  tags:
    - backstage
spec:
  owner: "dev-hub-team"

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pipeline-demo
  description: "System for managing the pipeline-demo project"
  tags:
    - pipeline-demo
spec:
  owner: "dev-hub-team"

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-hub-team
  description: "Development Hub Team"
spec:
  type: team
  members:
    - gaikwadgaurav12495
  children: []
